camera0: 4
camera1: 6
frame_width: 640
frame_height: 480
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 3.00
checkerboard_rows: 6
checkerboard_columns: 8
cooldown: 100
